apiVersion: v1
kind: Deployment
metadata:
  name: restapi-deployment
  labels:
    app: restapi
spec:
  replicas: 10
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapi-container
          image: neeraj870/restapi:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  type: ClusterIP
  selector:
    app: restapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
